name: Deploy_ISS_ITA

#controls when the workflow will run
on:

  #Allow you to run this workflow manually from the Actions tab
  workflow_dispatch:

#A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #This workflow has a single job called "build"
  build:
    #The type of runner that the job will run on
    runs-on: 
      - self-hosted-ita

    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Dotnet Build 
        shell: cmd
        run: dotnet build --configuration Release

      - name: Dotnet Publish
        shell: cmd
        run: |
          dotnet publish -c Release -o .\TestDeploy

      - name: Deploy to IIS
        shell: cmd
        run: |
          iisreset /stop
          xcopy /s /y .\TestDeploy\* C:\inetpub\wwwroot\HelloWorldAPI
          iisreset /start

